// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxBhAGxJeCqN8mtYOayifRrDLWk0JSTc',
    appId: '1:390385311760:web:8d46c0562a2eef49ce2a95',
    messagingSenderId: '390385311760',
    projectId: 'todo-app-a9c0c',
    authDomain: 'todo-app-a9c0c.firebaseapp.com',
    storageBucket: 'todo-app-a9c0c.appspot.com',
    measurementId: 'G-ELF2B2TKDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmBTaPrNtWUVN8D5gMCwG38gZMKawqaA',
    appId: '1:390385311760:android:0a12c86efb7e2e86ce2a95',
    messagingSenderId: '390385311760',
    projectId: 'todo-app-a9c0c',
    storageBucket: 'todo-app-a9c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXW-ksfDl6eE4EIHoZIaeXUO8f5jUklgc',
    appId: '1:390385311760:ios:1b280587ea8f23ecce2a95',
    messagingSenderId: '390385311760',
    projectId: 'todo-app-a9c0c',
    storageBucket: 'todo-app-a9c0c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXW-ksfDl6eE4EIHoZIaeXUO8f5jUklgc',
    appId: '1:390385311760:ios:66492fdead2da73cce2a95',
    messagingSenderId: '390385311760',
    projectId: 'todo-app-a9c0c',
    storageBucket: 'todo-app-a9c0c.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
